
export default function About(){
    return(
        <div>
            <div className="homepage"> 
                <h1>ABOUT ME</h1>
            </div>
            <div className="aboutpage">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta quia, non deserunt minus beatae possimus esse facilis voluptates. Rerum ratione facere est sunt aliquid dignissimos eos repellendus, saepe sequi? Debitis natus tempora eaque nihil maxime aut dolor neque! Ex, architecto quisquam modi laudantium qui quae dicta, dolore minima a deleniti recusandae illum. Mollitia voluptatum officiis cumque illo expedita commodi quisquam explicabo non velit molestias quis officia, saepe corporis quod impedit ducimus quas quibusdam eaque perferendis odio provident sapiente accusantium aliquam iure. Magni quidem, suscipit eius ipsa odit in illum nisi deleniti praesentium animi nam quibusdam officiis similique mollitia corporis! Placeat similique tenetur quis deleniti natus vitae qui neque libero beatae voluptas est aliquid, sequi nisi ipsum exercitationem, nam fugiat laboriosam nobis, architecto dolorem hic cum? Quisquam laboriosam distinctio in enim sapiente tempore rerum praesentium id, quidem non ipsa molestiae dicta consequuntur impedit voluptatem, eligendi veniam veritatis vitae nobis, autem laborum ad! Beatae minima laboriosam omnis quam asperiores voluptatibus deserunt, maxime atque earum vero debitis ea praesentium ut assumenda saepe, porro temporibus ipsum ab vitae iste iusto! Esse vitae a accusamus aliquam quis. Porro nostrum facilis cum repellendus laborum repellat quibusdam non corporis perferendis ea quam in obcaecati qui, fugiat ratione nihil cupiditate odit enim voluptatem quo, dolores magnam eius molestias doloribus. Fugit minima quo quod ex ut maiores laborum vitae blanditiis quasi sunt necessitatibus, ratione, neque sed voluptatem aliquid pariatur magnam vel praesentium. Aliquid minima velit consectetur impedit, accusamus aut officiis quisquam labore autem iusto, soluta, deleniti a possimus. Molestiae quo est libero? Debitis doloremque repudiandae nobis enim labore. Libero illum natus ab magni labore modi ipsum explicabo error, accusantium doloribus neque ad consequuntur aspernatur adipisci totam laborum esse quis quisquam voluptatum aut exercitationem atque cumque nam! Veritatis hic optio aperiam et corporis amet ad beatae dolor distinctio consequatur magni, voluptate quia esse? Minima maxime commodi, molestias, tempora perspiciatis consectetur ullam fugiat ipsa ex iure deserunt similique laudantium reiciendis rerum veniam ea labore! Ad in facere et blanditiis error! Atque possimus, inventore eveniet consequatur culpa, totam praesentium ab commodi deserunt numquam quo, dolorem soluta iste quasi unde in? Eum animi eligendi voluptate pariatur quidem officiis culpa natus fugit neque laboriosam odio maiores, nesciunt unde itaque deserunt exercitationem illum a at ducimus! Fugiat corrupti cumque eius provident recusandae, deserunt repudiandae. Commodi deserunt fugiat necessitatibus deleniti, nisi repudiandae dolorum odit quas sequi illo, provident illum nobis tenetur. Perspiciatis ipsum voluptatem vitae nemo.</p>
            </div>
        </div>
        
    )
}